### ISSUE TITLE
Consistent animation issues

### ISSUE THREAD

**Issue by VpSnipes** [dtzxporter/cast#80] opened 2024-12-18 05:05 UTC
Each time the asset is imported (Helldivers 2), using this "Cast" model/animation system, it has proven nothing but problematic. 

From it being small:
![image](https://github.com/user-attachments/assets/09ae2eef-a13d-4ca4-befd-c91f6ce073fc)

To it straight up losing the head:
![image](https://github.com/user-attachments/assets/1d31b454-8cec-4b3c-9a34-6ef038a23172)

Or it growing and shrinking rapidly then spiking to a new location from a previously loaded animation, despite the settings telling it to OVERWRITE the previous data.
![image](https://github.com/user-attachments/assets/9ef8b26e-c3da-4372-a5f1-9a7b3990ec8c)
![image](https://github.com/user-attachments/assets/1f8b5aed-7c0f-45b5-8c77-e69be98326bc)

Of all the formats I've seen, this is by far one of the worst. I'm not sure what was planned with it, the utilization is sub-par to your other formats which promise such tremendous results, what happened? These animation issues are CONSISTENT across any game ported to maya regardless of what settings are used for both the model or animation.

I'm not sure what's going on with it, but no matter what settings are changed for the animation side, it ALWAYS balls up now and it doesn't matter if I restart Maya or not. Blender has worse issues and I'm not sure I even want to touch on that give how god-awful blender is to begin with.

EDIT: The more that's loaded the worse it gets btw..
![image](https://github.com/user-attachments/assets/d31d6777-2750-4d90-b9b0-fb52c1acc1b1)
![image](https://github.com/user-attachments/assets/b28268fc-12c6-4c20-b045-d15621b43f3b)

You are genuinely better off writing to SMD or FBX for animation and model data, not creating an entirely new gltf format.

**Comment by dtzxporter** [comment] 2024-12-18 05:44
Did you ever stop and think to report a bug in Diver, instead of blaming the format it's exported to?

Cast is used in hundreds thousands of model ports across games like call of duty, doom eternal, evil within, all of the snowdrop games.

I don't appreciate your hostility especially when you clearly think that you should blame an issue on the format instead of actually providing any usable information to debug the issue, such as the animation and models that you have issues with.

I'm going to close this issue, because I know thousands of people who use cast daily and have no issues with it. If you want to provide real bug reports (for Diver clearly) you should come to discord and provide the necessary information.

**Closed** 2024-12-18 05:45 UTC

**Comment by VpSnipes** [comment] 2024-12-18 05:58
If the other provided formats work as intended, and this format does not (more specifically for animation logic). Then wouldn't that be a format issue? As for the debug errors, there aren't any, none in blenders console or Mayas. This happens with anything brought over to the Cast format animation wise. This issue is NOT present in SEAnim, this issue also persists in Blender (Maya version 2019, Blender version 3.0+ currently 4.2, 3.0 still has this same issue.)

I don't believe Diver is incorrect in writing out the data, as animations DO occasionally work but do not utilize proper rotation or translation logic when played or scrubbed via the timeline. I wouldn't blame the format if Diver WAS able to write to the other versions (such as SEAnim which I believe was present earlier in release, though it still had some funky issues with how Diver handled the bone logic at that time.) I haven't ever seen SEAnim scrunch animations like this, or completely eat parts of the model.

I'm not sure WHAT kind of debug info I can give when the console doesn't output any errors or problems when it's ported to the scene, which is telling me the tool is trying to load it "as intended" and something is going wrong.

So yes, I'm going to blame how the format was written. Especially when your other formats were streamlined and straight forward to utilize with frighteningly little errors or problems if any at all (in the time working with them). I'm not the only one with weird issues like this, as I know a few others who have ported from other games (The Evil Within 1/2, Helldivers 2, Doom Eternal (not 2016 given we need to remake IK), and lastly CoD, Cold War was all I tried with Cast and that had some really funky issues with legs disappearing.)

**Comment by dtzxporter** [comment] 2024-12-18 06:02
Cast is literally an improved SEAnim. If you're having issues with a specific game and it's imports, you need to provide the full model name, and animation name of the asset you're trying to import.

I've been working with the call of duty maintainers and helping improve cast integration, but the issue is it highly depends on the version of greyhound you have, old files will _not_ work properly.

If you want to debug specific issues, provide the assets so people can actually test what you say.

If the console doesn't output any errors, then it's the data itself.

**Comment by VpSnipes** [comment] 2024-12-18 06:13
> I've been working with the call of duty maintainers and helping improve cast integration, but the issue is it highly depends on the version of greyhound you have, old files will not work properly.

I'm using a version of Greyhound nabbed from the discord Fork of it for MW3 2024, and BO6 (which I believe uses a separate tool system to grab the assets). This has issues with any assets loaded to Maya regarding animation, as forementioned with disappearing legs or scrunched models.

>If you want to debug specific issues, provide the assets so people can actually test what you say.
>
>If the console doesn't output any errors, then it's the data itself.

Assets for Helldivers 2 (since this is the relevant topic to the post), you can pull anything from it as mentioned before, this isn't just a single model with this issue. I just ended up showing the `cha_stalker` located in `models/content/fac_bugs/cha_stalker` paired with its animation set inside `animations/content/fac_bugs/cha_stalker`. 

Import settings are as shown in the above main post, if it's an issue with the tool then I'm the idiot for blaming the format. Though I don't believe that's the case given animations do load correctly from time to time, though they have a higher chance of going ape-shit if another is loaded on top of them. If all animations were super corrupt, then I'd get consistent issues with translation and rotation data which isn't the case here as the same animation could be loaded 5 times and each one yields a completely different result.

> No actual bug reports have been filed, no clear reproduction steps, etc. I also use cast daily on all of the tools I maintain in both blender and maya.

In the aforementioned post, I did clarify that you could load any animation from any game to achieve this issue. If this isn't an issue present with Maya 2020+ then it's a maya problem on earlier versions. I'm using 2019, though I have 2022 and 2024.

**Comment by dtzxporter** [comment] 2024-12-18 06:17
Cast and seanim for that matter also don't respect the importance of playback setting, cast has separate menu options to configure its import. (Make a feature request if you want it to respect Maya's playback options)

Import reset - resets the model before importing the next animation clearing the data

And import at time, which imports the next animation at the given time on the timeline.

I'll look at a few animations from helldivers but again, it's more than likely an issue with Diver, or, it's an additive animation which needs to be blended.

**Comment by VpSnipes** [comment] 2024-12-18 06:23
> I'll look at a few animations from helldivers but again, it's more than likely an issue with Diver, or, it's an additive animation which needs to be blended.

I appreciate you taking the time to look into this, I do adore the formats you create as it has made creating content stupid quick. I just can't wrap my head around HOW or WHY this is wanting to do what it's doing, in both Maya and Blender. As for the additive animations themselves, it may be a good idea to flag them with an asterisk or an underscore to at least differentiate them (if at all possible).

> Import reset - resets the model before importing the next animation clearing the data

I can give this a shot again, though in my time doing so it has still yielded the unfortunate results you see above.

I'd also like to take a second and apologize for coming off the way i did in the first post as it's from concern with the options we have at our disposal for porting assets especially when one worked SUPER well and made the process fast and efficient. I have no doubt this is a simple issue to be resolved especially given your talents as a programmer.

**Comment by dtzxporter** [comment] 2024-12-18 06:35
Animations are complex, the reason why cast (and before that seanim exist) is because other formats require you have certain information present, which isn't how all games operate (most of the time the important information is yeeted until later) 

(GLTF/FBX/SMD etc require that you have the target skeleton, and don't support additive or retarget animations period)

Just because a tool exports properly and doesn't error out, just means that the data lines up in a way that doesn't cause an issue with the tool (which can happen in a thousand different ways) I can't visually inspect the thousands of animations that my tools produce, so I have to rely on people submitting clear reproduceable steps to their problems instead of just saying 'it doesn't work' or completely ignoring the issue entirely and not notifying me about it.

Call of duty is tricky, because I'm no longer active in the community, and I only get information relayed to me by it's maintainers. Though I will say that SEAnim in blender was always broken, the math straight up didn't create the correct frames,, and I only realized that working on cast.

I'm of course willing to help investigate and improve cast or the tool depending on where the issue is, but I don't waste my time when people just say 'it's broken'.

I'll spend some time soon trying to find some of the reproductions you have, but _please_ make sure both the cast plugins _and_ tool you export with are up to date. I update the plugins frequently, and cast has a backwards compatibility guarantee. 

I won't be able to look at it immediately (because it's the holidays) but I'll see what I can do.

I currently test in blender 3, 4.x, and maya 2024, but I have people reporting using maya 2020 successfully.

**Comment by VpSnipes** [comment] 2024-12-18 06:47
> I'm of course willing to help investigate and improve cast or the tool depending on where the issue is, but I don't waste my time when people just say 'it's broken'.
>
> I'll spend some time soon trying to find some of the reproductions you have, but please make sure both the cast plugins and tool you export with are up to date. I update the plugins frequently, and cast has a backwards compatibility guarantee.
>
> I won't be able to look at it immediately (because it's the holidays) but I'll see what I can do.
>
> I currently test in blender 3, 4.x, and maya 2024, but I have people reporting using maya 2020 successfully.

Hey enjoy the holidays man, my issue can wait if you're not able since it's far more important to spend that time with family and friends.

As for the Cast Plugin and tool, both are up-to-date, as they were grabbed today to test it. I can provide the files via googledrive here if needed? Hopefully that can sort something out on that end.

[https://drive.google.com/file/d/13pMowLYHgdZ4tnnqNZVC_22TfH6VciG9/view?usp=sharing](url)

**Comment by dtzxporter** [comment] 2025-01-03 01:20
In case you haven't noticed, I've updated diver to support more animations from helldivers 2 (they are additive and they've been broken due to the way the game does additive animations)

No issues with cast have been observed! 😄 

If you update and re-export the animations, you'll see many more are available (I tested a bunch, there may still be specific ones that aren't supported), the additive ones that are now working will have very little movement in most joints as it's meant to be blended with other animations (you can do this in maya with layers, or blender with the NLA editor).

The game is dumb, and has a weird system for additives (unused bones are set to 0, 0, 0. which is why the model disappeared from you. Cast was just doing the correct thing.)

If you come across more animations, I can investigate those in Diver on a case by case basis.

Happy new years.

**Comment by VpSnipes** [comment] 2025-01-03 07:25
Happy new years! Thanks for the update on the toolset, looking forward to experimenting with it later, really odd how they do their additives as that's a super fucky way of going about it.

Irrelevant to the topic here, I'd like to ask what you consider when making a toolset for a game, is it based on the compiled data or ready documentation before designing/building a tool? or do you go in raw and just beast mode it? I've got extensive documentation on Dead Space (original Trilogy) and I've been trying to find someone who'd want to take a crack at the animations from the game as they're mostly figured out yet still have some issues here and there.
