### ISSUE TITLE
The animation still has the wrong bone transformation

### ISSUE THREAD

**Issue by PavielKraskouski** [dtzxporter/cast#47] opened 2024-01-03 15:50 UTC
After installing version 1.31, I still see animation issues.

Protruding edges of the knuckles:

![image](https://github.com/dtzxporter/cast/assets/9061796/b27bfb39-e0ad-4b02-be30-8656414cdfe7)

![image](https://github.com/dtzxporter/cast/assets/9061796/a7ebe1a1-5d33-4c26-848c-0b07bac7ad89)

The knuckles intersect with the hand:

![image](https://github.com/dtzxporter/cast/assets/9061796/b42ad5bd-872a-4163-9fb6-20207bb3596a)

![image](https://github.com/dtzxporter/cast/assets/9061796/4bb35a14-289e-4c41-8e0a-9b7fdc19f021)

![image](https://github.com/dtzxporter/cast/assets/9061796/25dc0cde-9c66-4980-b182-a8e2ac2d9b38)

**Comment by dtzxporter** [comment] 2024-01-03 19:16
This should be fixed in v1.32. You'll have to re-import the model _again_. This time I compared the model against Autodesk Maya's FBX and checked that all deformed vertices match blender's import. The issue is related to scales again because blender has a non-industry standard bone system. Cast now emulates one, and produces the identical result in blender. I'll leave this open until you respond.

**Comment by PavielKraskouski** [comment] 2024-01-03 19:46
Now something wrong with fingers:

![image](https://github.com/dtzxporter/cast/assets/9061796/04baed86-29f8-4ba1-9e94-15852f33e0ce)

And this is how it should be:

![image](https://github.com/dtzxporter/cast/assets/9061796/d0227908-169f-4592-b1ad-1b4a5e79fce1)

**Comment by dtzxporter** [comment] 2024-01-03 19:51
What model did you use to import?

The one in-game is `doom_marine_3p` which has different hand joints to `doom_cine`.

**Comment by PavielKraskouski** [comment] 2024-01-03 20:08
Yes, I used to import `doomslayer_cine`. Now I tried to import `doom_marine_3p`, and everything seems to be working correctly. It is not clear why this model does not have a launcher on the back. And maybe you can tell me how to determine the compatibility of animation and model.

**Comment by dtzxporter** [comment] 2024-01-03 20:13
Because the launcher has separate model files that are merged onto the `launcherbase_part01_lf` joint at runtime by the game based on which one you have. Merging 'set' pieces will eventually be a cast feature as it's used a lot in games which have lots of mtx/skins. Determining which model goes with what animation is not always possible to determine without looking into the game's raw files or using trial & error. Either way, I am glad this issue is resolved. I will mark this as solved.

**Closed by dtzxporter** 2024-01-03 20:13 UTC
Labels: bug, blender
